### PR TITLE
provide make-entity

### PR DESCRIPTION
**Pull request by Bogdanp**
@yurkobb please let me know what you think re the use case you mentioned in https://github.com/Bogdanp/deta/issues/14#issuecomment-738831811 .

### CODE REVIEW

**Comment by yurkobb** [comment]
Thanks a lot! I'm experimenting with it right now - will get back soon with some feedback!

**Comment by yurkobb** [comment]
I have incorporated `make-entity` in all queries that span multiple tables; as first step - still retaining the explicit unpacking of fields from `in-query`. This already makes my code slightly less "boilerplaty", for instance:

```diff
 (define (load-products-i18n q)
   (for/list ([(uuid sku price currency vendor attributes _ lang title description)
               (in-query (db-conn) q)])
-    (make-product #:uuid uuid
-                  #:sku sku
-                  #:price price
-                  #:currency currency
-                  #:vendor-ref vendor
-                  #:attributes attributes
-                  #:lang (if (not (sql-null? lang))
-                             (make-product-i18n #:product uuid
-                                                #:lang lang
-                                                #:title title
-                                                #:description description)
-                             #f))))
+    (define the-product
+      (make-entity (db-conn)
+                   product-schema
+                   (list uuid sku price currency vendor attributes)))
+    (cond
+      [(sql-null? lang) the-product]
+      [else
+       (set-product-lang the-product
+                         (make-entity (db-conn)
+                                      product-i18n-schema
+                                      (list uuid lang title description)))])))
+
```

So, even in such scenario it is definitely useful, so +1 to merging it!

# Further thoughts

I also envisioned constructing helper functions or macros for "unpacking" composite queries into sets of columns per entity, that could in turn use `make-entity` under the hood (or simply provide a column list for use with `make-entity`); I'm not yet sure how these would look. But exposing `make-entity` enables such possibilities. I suspect maybe access to the schema struct from `private/schema.rkt` would also be needed for determining the set of relevant fields with `schema-fields` - but that's all part of a broader question of idiomatically handling composite queries with possibly nested entities, which is rather out of scope for this PR :)

## Virtual fields

Another thing that may be relevant (something that was also touched on a little [in the discussion on virtual fields](https://github.com/Bogdanp/deta/issues/35#issuecomment-729183976)) is the ability to `project-onto`  virtual fields too. Since `make-entity` and `project-onto` are somewhat similar and related, this could in theory also apply to `make-entity`. The example with `project-onto` we discussed was when a certain virtual field's value results from a related table in a join query. I had precisely this situation in my code where I would `SELECT` a related and/or a computed field like `(price * quantity) AS sum` that directly corresponds to a virtual field on the schema.

It would be nice if `project-onto` and `make-entity` could potentially also allow virtual fields (perhaps toggled with a keyword flag?). Again, this is probably out of scope for this PR - more like potential ideas to discuss.

**Comment by yurkobb** [comment]
Thinking about this more - I have some additional comments about potential other uses of `schema-fields` and `make-entity`:

1. While the initial idea to use `make-entity` came from the database-to-entity use case, it can be equally useful in building semi-automatic deserialization of entities from transport (json, xml, etc). By combining `schema-fields` with something like `make-entity` one can easily construct entities received via HTTP (provided they are validated) without having to explicitly list the fields - providing the schema name would suffice.
2. However, `make-entity` expects "raw" data from the db, while for json-and-friends a similar function accepting rackety values would be needed. The normal "smart" `make-<type>` constructor could work, although using keyword arguments _programmatically_ is a bit clunky:

```racket
;; An utility function to deserialize entities I use
(define/contract (hash->entity the-hash constructor kws)
  (-> hash? procedure? (listof keyword?) entity?)
  (define sorted-kws (sort kws keyword<?))
  (define vals (for/list ([kw (in-list sorted-kws)])
                 (hash-ref the-hash (string->symbol (keyword->string kw)))))
  (keyword-apply constructor sorted-kws vals '()))
```
(EDIT: currently this requires specifying keywords manually, but it can be easily made automatic by using `schema-fields` along with the `field` struct accessors from `private/field.rkt`.)

So I was thinking that maybe `make-entity` could have a sister function accepting the same values for the fields as the "smart" keyword-based constructor, but via a dict? In fact it could be a simple wrapper around the smart constructor to retain the contracts. Something like:
```racket
(define/contract (dict->entity the-dict schema)
  (-> dict? schema? entity?)
  ...)
```

What do you think?

P.S. Again, this is probably all about another future PR.

**Comment by Bogdanp** [comment]
Thanks for trying this out and sharing your thoughts.

> It would be nice if project-onto and make-entity could potentially also allow virtual fields (perhaps toggled with a keyword flag?). Again, this is probably out of scope for this PR - more like potential ideas to discuss.

I agree. This would be a nice addition.

> So I was thinking that maybe make-entity could have a sister function accepting the same values for the fields as the "smart" keyword-based constructor, but via a dict? In fact it could be a simple wrapper around the smart constructor to retain the contracts. Something like:

I think that once `schema-fields` and the field accessors are made public, you won't need an analog built into deta to be able to do this, because every field knows what its own keyword is. I'll merge this and work on making those things public next weekend.

Thanks again!

**Comment by yurkobb** [comment]
Thanks to you for all the work!

Regarding making `schema-fields` public, it seems there's one more piece needed - a way to get from an entity instance to its schema (I'm looking at how [`insert-entity!` does this](https://github.com/Bogdanp/deta/blob/master/deta-lib/query.rkt#L62) now). It involves poking in `entity-meta` but I'm not sure it makes sense to make all that public too - it seem unnecessary. Maybe just a simple function like `entity-schema`?

**Comment by yurkobb** [comment]
P.S. Just as an example of use for the `schema-fields` part - I went ahead and `require`d everything I needed to have access to `schema-fields`, `field-kw`, `field-getter`, and now I can do things like:

```racket
(register-serializer! ;; a recursive serialization thing
 'cart-item
 (lambda (cart-item)
   (~> (entity->hasheq cart-item) ;; defined in terms of `schema-fields` etc.
       (hash-update 'sum number->price)
       (hash-remove 'cart)))
 jsexpr->cart-item) ;; old explicit code

(register-serializer!
 'cart
 (lambda (cart)
   (~> (entity->hasheq cart)
       (hash-update 'created moment->iso8601)
       (hash-update 'sum number->price)))
 jsexpr->cart)
```

Then down the road I just can call the generic serializer and it traverses everything (cart containing items referring products containing images referring alt-text translations...) and calls the the appropriate functions on them to get a nice `jsexpr` tree.

**Pull request merged**
