### PR TITLE
query: add `select-for-schema' and `project-virtual-fields'

### PR DESCRIPTION
**Pull request by Bogdanp**

### CODE REVIEW

**Comment by Bogdanp** [comment]
@yurkobb let me know if you have any thoughts on these new operators. 

Given a schema like

```racket
(define-schema order
  ([id id/f #:primary-key #:auto-increment]
   [customer-email string/f]
   ... ;; many fields here
   [status symbol/f #:virtual]
   [payment-status symbol/f #:virtual]))
```

one can use the them to join into tables to grab data for the virtual fields and then project that data onto entities

```racket
(~> 
 (from order #:as o)
 (join status #:as os #:on (= os.order-id o.id))
 (join payment-status #:as ps #:on (= ps.order-id o.id))
 (select-for-schema 
  order 
  #:from o
  #:override ([status os.status]
              [payment-status ps.status]))
 (project-virtual-fields))
```

Not sure how I feel about the name `#:override` in `select-for-schema` yet.

**Comment by yurkobb** [comment]
Wow, this is great! Some thoughts:

1. It frees me from the need to manually specify all schema fields when "unpacking" the result of a join query onto a single schema with virtual fields; which is especially great in case of schema changes (the query code doesn't need to change with this approach).
2. In the case of multi-schema query (nested/related objects), the "unpacking" probably needs to happen manually anyway.
3. As a very hypothetical idea, I could imagine `select-for-schema` supporting specifying more than one schema (or some kind of "chaining" of `select-for-schema`s); however, we would probably need to add something like `in-entities/multiple` to return multiple values (one value per schema) as a result - not sure if this is a good idea or not...
4. Regarding the name of the `#:override` keyword - for me it feels a little too strong, kind of like the `!important` in css. But it's not a big deal. As per alternatives, things like `#:project`, `#:project-fields`, `#:(re)map` came to mind. However, with these names I have a feeling that an opposite order of specifying the fields would make sense (sql field -> schema field) - but I'm not sure.
5. Do I understand correctly that `#:override` is not meant to be specific to virtual fields only? On the other hand, if `#:override` operated only on virtual fields, it could be possible to have `(project-virtual-fields)` be automatically implied by `#:override`.

It seems like I'm always asking for more:) It is definitely useful for me as is! Just sharing some "brainstorming" material just in case.

Thanks for all the work!

**Comment by yurkobb** [comment]
One more thing - a separate but related aspect - adding custom `SELECT ... AS something` columns on top of what the selected tables contain - like `(as (* item.quantity product.price) sum)` and mapping them onto virtual fields is sometimes needed. Would `#:override` be an appropriate place to specify these too?

**Comment by Bogdanp** [comment]
> Do I understand correctly that #:override is not meant to be specific to virtual fields only? On the other hand, if #:override operated only on virtual fields, it could be possible to have (project-virtual-fields) be automatically implied by #:override.

> One more thing - a separate but related aspect - adding custom SELECT ... AS something columns on top of what the selected tables contain - like (as (* item.quantity product.price) sum) and mapping them onto virtual fields is sometimes needed. Would #:override be an appropriate place to specify these too?

Right on both counts. The overrides let you specify select expressions for any field.

**Comment by Bogdanp** [comment]
Maybe `#:custom` (or `#:customizing`, as in `(select-for-schema foo #:from f #:customizing ...)`) would be a better keyword.

**Pull request merged**
